[meta]
engine = "1"

[layout]
default = "aurora_showcase"

[[layout.variants]]
id = "aurora_showcase"
display_name = "Turntable Showcase"

[layout.variants.structure]
type = "row"
spacing = 24
align = "center"
fill = true

[[layout.variants.structure.children]]
type = "component"
id = "thumbnail"

[[layout.variants.structure.children]]
type = "column"
spacing = 14
fill = true

  [[layout.variants.structure.children.children]]
  type = "component"
  id = "title"

  [[layout.variants.structure.children.children]]
  type = "component"
  id = "metadata"
    [layout.variants.structure.children.children.params]
    show_state = "true"
    show_state_label = "false"

  [[layout.variants.structure.children.children]]
  type = "component"
  id = "timeline"
    [layout.variants.structure.children.children.params]
    centered = "false"
    separator = "false"

  [[layout.variants.structure.children.children]]
  type = "component"
  id = "playback_controls"
    [layout.variants.structure.children.children.params]
    centered = "true"

  [[layout.variants.structure.children.children]]
  type = "spacer"
  size = 6

  [[layout.variants.structure.children.children]]
  type = "component"
  id = "skin_warnings"

  [[layout.variants.structure.children.children]]
  type = "component"
  id = "skin_error"

  [[layout.variants.structure.children.children]]
  type = "component"
  id = "thumbnail_error"

  [[layout.variants.structure.children.children]]
  type = "component"
  id = "error"

[[layout.variants]]
id = "aurora_compact"
display_name = "Stacked Compact"

[layout.variants.structure]
type = "column"
spacing = 16
align = "center"
fill = true

[[layout.variants.structure.children]]
type = "component"
id = "thumbnail"

[[layout.variants.structure.children]]
type = "component"
id = "title"

[[layout.variants.structure.children]]
type = "component"
id = "metadata"
  [layout.variants.structure.children.params]
  show_state = "false"

[[layout.variants.structure.children]]
type = "component"
id = "timeline"
  [layout.variants.structure.children.params]
  centered = "true"

[[layout.variants.structure.children]]
type = "component"
id = "playback_controls"
  [layout.variants.structure.children.params]
  centered = "true"

[[layout.variants.structure.children]]
type = "component"
id = "skin_warnings"

[[layout.variants.structure.children]]
type = "component"
id = "skin_error"

[[layout.variants.structure.children]]
type = "component"
id = "thumbnail_error"

[[layout.variants.structure.children]]
type = "component"
id = "error"
